language: node_js
node_js:
- '0.10'
before_script:
- npm install bower
- node_modules/bower/bin/bower install
script: node_modules/grunt-cli/bin/grunt travis
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: A6IgZ68oxRaIk3VA9yUaWODlgJ4qA8EGP4yD4cHfzJU/qkZhaBoYjUcQW5uMyfQ5WyPaJp2L4xS8LgXZ3bkbgrYkmv6zwCJI7eTNoN7AV8WPtWd3FHs0wVdx0Z5YRId7TXBVkgIQP9Gon2tOeYHYmQHkg8BcSd3qD3xYKHEisp0=
  app: ateliesteste
env:
  global:
    #COVERALLS_REPO_TOKEN
    - secure: "Yad7YuAOmrknS9pb49D5rPf5pR3MRbEPgvJG0Omd5aYH3i5ps43RkkoQvtVi+P+HDtoIQA20a2LADirN9Lhanm75xXDldftGR85JFolzRBP/atxVyaG49ip5ylU/i3j07EYyEjopY1eBEnmPe7L7dES7vDBZXXE16MJDAizaZhI="
