language: node_js
node_js:
- '0.10'
before_install:
- echo "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
- echo "Travis build id is $TRAVIS_BUILD_ID"
before_script:
- node_modules/bower/bin/bower install
- ls -la
script:
- node_modules/grunt-cli/bin/grunt travis:compileLintAndTest --no-color --verbose
- node_modules/grunt-cli/bin/grunt travis:reportCoverage --no-color --verbose
- ls -la
- gem install --version 0.8.9 faraday #necessary for travis-artifacts to work
- gem install travis-artifacts
- travis-artifacts upload --path log --target-path $TRAVIS_BUILD_ID
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: A6IgZ68oxRaIk3VA9yUaWODlgJ4qA8EGP4yD4cHfzJU/qkZhaBoYjUcQW5uMyfQ5WyPaJp2L4xS8LgXZ3bkbgrYkmv6zwCJI7eTNoN7AV8WPtWd3FHs0wVdx0Z5YRId7TXBVkgIQP9Gon2tOeYHYmQHkg8BcSd3qD3xYKHEisp0=
  app: ateliesteste
  strategy: git
env:
  global:
    #COVERALLS_REPO_TOKEN
    - secure: "Yad7YuAOmrknS9pb49D5rPf5pR3MRbEPgvJG0Omd5aYH3i5ps43RkkoQvtVi+P+HDtoIQA20a2LADirN9Lhanm75xXDldftGR85JFolzRBP/atxVyaG49ip5ylU/i3j07EYyEjopY1eBEnmPe7L7dES7vDBZXXE16MJDAizaZhI="
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=travisatelies"
    #ARTIFACTS_AWS_ACCESS_KEY_ID
    - secure: "Yh1FvYqeL7gYCtvq5b4P1wfbAMvI1RldXGzkqLv/eBUyGGRa/B7x5M2zVSdXK20svMMEM+7cNSFWJUpktTZM/UfEZ9Ag5XB8rp67KZ3dlb8WDY99/vBt92Xx1tFazA2OnMX4whrh0jqZIQutv5Pbxr90vXoGsfDlE2P6nCAqGbU="
    #ARTIFACTS_AWS_SECRET_ACCESS_KEY
    - secure: "MKJXoYXyQS5NdInNpUV9Zzz2YRzZPYFAKuLuMbA9y8FOB0FydnjnecjjKBlyj4qL+LRCLV4q8OcCil2WdI7BXEQvNuqdul75gcbqQfnvV5hUTyUxSkXC/8nUfZ9I9ZZVDtwvK1JwLf+E0AwSVOrgUX/oWmlfw9TCA1eX1weVFYg="
