language: node_js
node_js:
- '0.10'
before_script:
- gem install travis-artifacts
- npm install bower
- node_modules/bower/bin/bower install
after_script:
- travis-artifacts upload --path build/build.tar.gz
after_failure:
- travis-artifacts upload --path debug/debug.log
script: node_modules/grunt-cli/bin/grunt travis
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: A6IgZ68oxRaIk3VA9yUaWODlgJ4qA8EGP4yD4cHfzJU/qkZhaBoYjUcQW5uMyfQ5WyPaJp2L4xS8LgXZ3bkbgrYkmv6zwCJI7eTNoN7AV8WPtWd3FHs0wVdx0Z5YRId7TXBVkgIQP9Gon2tOeYHYmQHkg8BcSd3qD3xYKHEisp0=
  app: ateliesteste
env:
  global:
    #COVERALLS_REPO_TOKEN
    - secure: "Yad7YuAOmrknS9pb49D5rPf5pR3MRbEPgvJG0Omd5aYH3i5ps43RkkoQvtVi+P+HDtoIQA20a2LADirN9Lhanm75xXDldftGR85JFolzRBP/atxVyaG49ip5ylU/i3j07EYyEjopY1eBEnmPe7L7dES7vDBZXXE16MJDAizaZhI="
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=travisatelies"
    #ARTIFACTS_AWS_ACCESS_KEY_ID
    - secure: "fOr5buNeO5kYxGAa8vi+X52EIqiNLIbxMuie10dGo1/RSnw1mQQNeSqx/Rxni0fJ8t5xqAFPZsWoJ6TvHTVq5lpSsj4/AO6gxCM1zPJgfklqb0JZ3IYZwiZAzYGdvyrlBk9ZWCcAE2Y6LyEqrF68v19gKGdwk5lcP+Pk5yHh+/s="
    #ARTIFACTS_AWS_SECRET_ACCESS_KEY
    - secure: "J9wyH3xQCd/AqBte51Pnq1mlBM1/vyk4mgAevkE08UXgvyessLhk+gcLT5oEs0ESfeWdPaTyv3P2MXN7h76Vg2ODo/pynUgtZF9QPO6tMkd2Gf63Ih7OX2z4+dqkRiQKKfawWg8oiOQCM4w34E5Ifv8N0Zgvsv4Y/c9azk+9Q1A="
